### ISSUE TITLE
incorrrect padding encoded in bech32

### ISSUE THREAD

**Issue by cryply** [brtastic/perl-bitcoin-crypto#2]
Hallo!

Perfect perl module!
Can you check why I am unable to decode this address bc1qcx0yh6nduwvjua9aq5ks296pkn8ddx585kdqnu

???

Thanks!

**Comment by cryply** [comment]
Found mistake line 156:
You removing zeroes from end while u need to do it from begining:
**$bits =~ s/0{$padding}$//;**
should be 
**$bits =~ s/^0{$padding}//;**

**Comment by cryply** [comment]
$bits =~ s/^0+//;
	
	# Bitcoin::Crypto::Exception::Bech32InputData->raise(
	# 	"incorrrect padding encoded in bech32"
	# ) if length($bits) % 8 != 0 || length($bits) < $length_padded - 4;

This helped

**Comment by brtastic** [comment]
Hi there @cryply ! Sorry for the late answer, glad you're enjoying the module.

The problem here is not actually a problem but documentation not being too clear on this. I myself had to dig in a bit to understand why it's not decoding as it should. What you're trying to do is decoding a segwit program, which has its own decoder here called `decode_segwit`.

The bech32 module itself has a couple of layers of encoding, namely:
- base32, which handles the alphabet and 5-to-8 transformation
- bech32, which handles checksums and human-readable (HRP) parts
- segwit, which handles segwit program numbering and validation

The address you provided is indeed valid, but the first letter `q` after `bc1` has to be treated differently than the rest of the address, and it is signaling segwit address of version 1. This special treatment is exactly what `decode_segwit` is doing. Splitting the decoder into these parts seemed a good idea implementation-wise, but may be a problem if it confuses enough people.

I've added this address as a test case to the module (passes on version 0.993) and I'll improve the documentation on bech32 package. Let me know if that fixes your problem

**Comment by brtastic** [comment]
Commits for this issue have been released to CPAN. Feel free to re-open the issue if you encounter any more problems.

**Comment by brtastic** [comment]
@cryply I've closed this issue to have the milestone completed, but I'm not sure if that won't encumber the visibility for my previous answer.

You should not use the method from your first comment as it will create problems for other cases of bech32 decoding. The test suite fails in many places with these changes and for good reason (it voids the bip173 compatibility). The documentation now explicitly states in two separate places not to use encode_bech32 and decode_bech32 for bitcoin segwit addresses, I think it should be enough for now to avoid misconceptions.
